"""add_exchange_rate_model

Revision ID: 009868e820e8
Revises: c2dd1e828db0
Create Date: 2026-02-28 12:15:04.368087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '009868e820e8'
down_revision: Union[str, Sequence[str], None] = 'c2dd1e828db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchangerate_currency_code'), 'exchangerate', ['currency_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchangerate_currency_code'), table_name='exchangerate')
    op.drop_table('exchangerate')
    # ### end Alembic commands ###
