"""fix_journal_entry

Revision ID: 1c9fe5ac53f4
Revises: 0136c8781ff3
Create Date: 2026-03-10 23:24:28.640787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c9fe5ac53f4'
down_revision: Union[str, Sequence[str], None] = '0136c8781ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journalentry', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journalentry', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
