"""Init Journal Entries

Revision ID: 25ebb615e060
Revises: 4ce6db009ed2
Create Date: 2026-02-28 08:55:48.077703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25ebb615e060'
down_revision: Union[str, Sequence[str], None] = '4ce6db009ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journalentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOIDED', name='journalentrystatus'), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscalperiod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journalentry_entry_date'), 'journalentry', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journalentry_transaction_id'), 'journalentry', ['transaction_id'], unique=True)
    op.create_table('ledgerline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journalentry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledgerline')
    op.drop_index(op.f('ix_journalentry_transaction_id'), table_name='journalentry')
    op.drop_index(op.f('ix_journalentry_entry_date'), table_name='journalentry')
    op.drop_table('journalentry')
    # ### end Alembic commands ###
