"""Add index to tracking_option_id

Revision ID: 334d10f1222d
Revises: 556f21849147
Create Date: 2026-03-03 23:36:53.257081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '334d10f1222d'
down_revision: Union[str, Sequence[str], None] = '556f21849147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ledgerline_tracking_option_id'), 'ledgerline', ['tracking_option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledgerline_tracking_option_id'), table_name='ledgerline')
    # ### end Alembic commands ###
