"""Add tracking models and link to ledger line

Revision ID: 556f21849147
Revises: 9f97553dfc95
Create Date: 2026-03-03 23:25:47.570895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '556f21849147'
down_revision: Union[str, Sequence[str], None] = '9f97553dfc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackingcategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackingoption',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['trackingcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ledgerline', sa.Column('tracking_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ledgerline', 'trackingoption', ['tracking_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ledgerline', type_='foreignkey')
    op.drop_column('ledgerline', 'tracking_option_id')
    op.drop_table('trackingoption')
    op.drop_table('trackingcategory')
    # ### end Alembic commands ###
