"""Add Fixed Assets and Depreciation Schedule

Revision ID: 618c37ee0304
Revises: ac37c610b3aa
Create Date: 2026-03-04 13:54:56.902191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '618c37ee0304'
down_revision: Union[str, Sequence[str], None] = 'ac37c610b3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixedasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('salvage_value', sa.Float(), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('asset_account_id', sa.Integer(), nullable=False),
    sa.Column('depreciation_expense_account_id', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation_account_id', sa.Integer(), nullable=False),
    sa.Column('tracking_option_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISPOSED', name='assetstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['asset_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['depreciation_expense_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['tracking_option_id'], ['trackingoption.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depreciationschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['fixedasset.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journalentry.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depreciationschedule')
    op.drop_table('fixedasset')
    # ### end Alembic commands ###
