"""add_tax_rate_model

Revision ID: 87a87c0a0edd
Revises: 34cd3e7f5149
Create Date: 2026-03-03 23:10:50.685081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87a87c0a0edd'
down_revision: Union[str, Sequence[str], None] = '34cd3e7f5149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxrate_name'), 'taxrate', ['name'], unique=False)
    op.add_column('billlineitem', sa.Column('tax_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billlineitem', 'taxrate', ['tax_rate_id'], ['id'])
    op.add_column('invoicelineitem', sa.Column('tax_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicelineitem', 'taxrate', ['tax_rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoicelineitem', type_='foreignkey')
    op.drop_column('invoicelineitem', 'tax_rate_id')
    op.drop_constraint(None, 'billlineitem', type_='foreignkey')
    op.drop_column('billlineitem', 'tax_rate_id')
    op.drop_index(op.f('ix_taxrate_name'), table_name='taxrate')
    op.drop_table('taxrate')
    # ### end Alembic commands ###
