"""multi_tenancy_upgrade

Revision ID: 94026c6e23a6
Revises: 009868e820e8
Create Date: 2026-03-02 19:01:12.973482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "94026c6e23a6"
down_revision: Union[str, Sequence[str], None] = "009868e820e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "base_currency_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("primary_color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tax_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)

    # Backfill Logic
    import uuid

    default_org_id = str(uuid.uuid4())
    op.execute(
        f"INSERT INTO organization (id, name, slug, base_currency_code, is_active, created_at) VALUES ('{default_org_id}', 'Default Org', 'default-{default_org_id[:8]}', 'NGN', true, now())"
    )

    op.add_column("account", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE account SET org_id = '{default_org_id}'")
    op.alter_column("account", "org_id", nullable=False)
    op.drop_index(op.f("ix_account_code"), table_name="account")
    op.create_index(op.f("ix_account_code"), "account", ["code"], unique=False)
    op.create_unique_constraint(None, "account", ["org_id", "code"])
    op.create_foreign_key(None, "account", "organization", ["org_id"], ["id"])
    op.add_column("bill", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE bill SET org_id = '{default_org_id}'")
    op.alter_column("bill", "org_id", nullable=False)
    op.create_foreign_key(None, "bill", "organization", ["org_id"], ["id"])
    op.add_column("billlineitem", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE billlineitem SET org_id = '{default_org_id}'")
    op.alter_column("billlineitem", "org_id", nullable=False)
    op.create_foreign_key(None, "billlineitem", "organization", ["org_id"], ["id"])
    op.add_column("companysettings", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE companysettings SET org_id = '{default_org_id}'")
    op.alter_column("companysettings", "org_id", nullable=False)
    op.create_foreign_key(None, "companysettings", "organization", ["org_id"], ["id"])
    op.add_column("customer", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE customer SET org_id = '{default_org_id}'")
    op.alter_column("customer", "org_id", nullable=False)
    op.create_foreign_key(None, "customer", "organization", ["org_id"], ["id"])
    op.add_column("exchangerate", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE exchangerate SET org_id = '{default_org_id}'")
    op.alter_column("exchangerate", "org_id", nullable=False)
    op.drop_index(op.f("ix_exchangerate_currency_code"), table_name="exchangerate")
    op.create_index(
        op.f("ix_exchangerate_currency_code"),
        "exchangerate",
        ["currency_code"],
        unique=False,
    )
    op.create_unique_constraint(None, "exchangerate", ["org_id", "currency_code"])
    op.create_foreign_key(None, "exchangerate", "organization", ["org_id"], ["id"])
    op.add_column("fiscalperiod", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE fiscalperiod SET org_id = '{default_org_id}'")
    op.alter_column("fiscalperiod", "org_id", nullable=False)
    op.drop_index(op.f("ix_fiscalperiod_name"), table_name="fiscalperiod")
    op.create_index(
        op.f("ix_fiscalperiod_name"), "fiscalperiod", ["name"], unique=False
    )
    op.create_unique_constraint(None, "fiscalperiod", ["org_id", "name"])
    op.create_foreign_key(None, "fiscalperiod", "organization", ["org_id"], ["id"])
    op.add_column("invoice", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE invoice SET org_id = '{default_org_id}'")
    op.alter_column("invoice", "org_id", nullable=False)
    op.drop_index(op.f("ix_invoice_invoice_number"), table_name="invoice")
    op.create_index(
        op.f("ix_invoice_invoice_number"), "invoice", ["invoice_number"], unique=False
    )
    op.create_unique_constraint(None, "invoice", ["org_id", "invoice_number"])
    op.create_foreign_key(None, "invoice", "organization", ["org_id"], ["id"])
    op.add_column("invoicelineitem", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE invoicelineitem SET org_id = '{default_org_id}'")
    op.alter_column("invoicelineitem", "org_id", nullable=False)
    op.create_foreign_key(None, "invoicelineitem", "organization", ["org_id"], ["id"])
    op.add_column("journalentry", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE journalentry SET org_id = '{default_org_id}'")
    op.alter_column("journalentry", "org_id", nullable=False)
    op.drop_index(op.f("ix_journalentry_transaction_id"), table_name="journalentry")
    op.create_index(
        op.f("ix_journalentry_transaction_id"),
        "journalentry",
        ["transaction_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "journalentry", ["org_id", "transaction_id"])
    op.create_foreign_key(None, "journalentry", "organization", ["org_id"], ["id"])
    op.add_column("ledgerline", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE ledgerline SET org_id = '{default_org_id}'")
    op.alter_column("ledgerline", "org_id", nullable=False)
    op.create_foreign_key(None, "ledgerline", "organization", ["org_id"], ["id"])
    op.add_column("user", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE \"user\" SET org_id = '{default_org_id}'")
    op.alter_column("user", "org_id", nullable=False)
    op.create_foreign_key(None, "user", "organization", ["org_id"], ["id"])
    op.add_column("vendor", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.execute(f"UPDATE vendor SET org_id = '{default_org_id}'")
    op.alter_column("vendor", "org_id", nullable=False)
    op.create_foreign_key(None, "vendor", "organization", ["org_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vendor", type_="foreignkey")
    op.drop_column("vendor", "org_id")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "org_id")
    op.drop_constraint(None, "ledgerline", type_="foreignkey")
    op.drop_column("ledgerline", "org_id")
    op.drop_constraint(None, "journalentry", type_="foreignkey")
    op.drop_constraint(None, "journalentry", type_="unique")
    op.drop_index(op.f("ix_journalentry_transaction_id"), table_name="journalentry")
    op.create_index(
        op.f("ix_journalentry_transaction_id"),
        "journalentry",
        ["transaction_id"],
        unique=True,
    )
    op.drop_column("journalentry", "org_id")
    op.drop_constraint(None, "invoicelineitem", type_="foreignkey")
    op.drop_column("invoicelineitem", "org_id")
    op.drop_constraint(None, "invoice", type_="foreignkey")
    op.drop_constraint(None, "invoice", type_="unique")
    op.drop_index(op.f("ix_invoice_invoice_number"), table_name="invoice")
    op.create_index(
        op.f("ix_invoice_invoice_number"), "invoice", ["invoice_number"], unique=True
    )
    op.drop_column("invoice", "org_id")
    op.drop_constraint(None, "fiscalperiod", type_="foreignkey")
    op.drop_constraint(None, "fiscalperiod", type_="unique")
    op.drop_index(op.f("ix_fiscalperiod_name"), table_name="fiscalperiod")
    op.create_index(op.f("ix_fiscalperiod_name"), "fiscalperiod", ["name"], unique=True)
    op.drop_column("fiscalperiod", "org_id")
    op.drop_constraint(None, "exchangerate", type_="foreignkey")
    op.drop_constraint(None, "exchangerate", type_="unique")
    op.drop_index(op.f("ix_exchangerate_currency_code"), table_name="exchangerate")
    op.create_index(
        op.f("ix_exchangerate_currency_code"),
        "exchangerate",
        ["currency_code"],
        unique=True,
    )
    op.drop_column("exchangerate", "org_id")
    op.drop_constraint(None, "customer", type_="foreignkey")
    op.drop_column("customer", "org_id")
    op.drop_constraint(None, "companysettings", type_="foreignkey")
    op.drop_column("companysettings", "org_id")
    op.drop_constraint(None, "billlineitem", type_="foreignkey")
    op.drop_column("billlineitem", "org_id")
    op.drop_constraint(None, "bill", type_="foreignkey")
    op.drop_column("bill", "org_id")
    op.drop_constraint(None, "account", type_="foreignkey")
    op.drop_constraint(None, "account", type_="unique")
    op.drop_index(op.f("ix_account_code"), table_name="account")
    op.create_index(op.f("ix_account_code"), "account", ["code"], unique=True)
    op.drop_column("account", "org_id")
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
