"""Add reconciled fields to ledger line

Revision ID: 9f97553dfc95
Revises: b51094de2336
Create Date: 2026-03-03 23:20:40.604304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9f97553dfc95"
down_revision: Union[str, Sequence[str], None] = "b51094de2336"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ledgerline",
        sa.Column(
            "is_reconciled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("ledgerline", sa.Column("reconciled_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ledgerline", "reconciled_at")
    op.drop_column("ledgerline", "is_reconciled")
    # ### end Alembic commands ###
