"""Add quantity to invoice and bill lines

Revision ID: a7151ea7b953
Revises: b4f6a30091e6
Create Date: 2026-03-04 14:00:57.702639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a7151ea7b953"
down_revision: Union[str, Sequence[str], None] = "b4f6a30091e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "billlineitem",
        sa.Column("quantity", sa.Float(), nullable=False, server_default="1.0"),
    )
    op.add_column(
        "invoicelineitem",
        sa.Column("quantity", sa.Float(), nullable=False, server_default="1.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoicelineitem", "quantity")
    op.drop_column("billlineitem", "quantity")
    # ### end Alembic commands ###
