"""Add Payroll and expense models with UUID

Revision ID: ac37c610b3aa
Revises: 334d10f1222d
Create Date: 2026-03-04 13:42:53.136594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac37c610b3aa'
down_revision: Union[str, Sequence[str], None] = '334d10f1222d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department_option_id', sa.Integer(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_option_id'], ['trackingoption.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payrollrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PAID', name='runstatus'), nullable=True),
    sa.Column('total_gross_pay', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('total_net_pay', sa.Float(), nullable=False),
    sa.Column('total_taxes', sa.Float(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journalentry.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscalperiod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenseclaim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date_incurred', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('tracking_option_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'PAID', name='expensestatus'), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['expense_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journalentry.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['tracking_option_id'], ['trackingoption.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('gross_pay', sa.Float(), nullable=False),
    sa.Column('tax_deduction', sa.Float(), nullable=False),
    sa.Column('benefits_deduction', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payrollrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslip')
    op.drop_table('expenseclaim')
    op.drop_table('payrollrun')
    op.drop_table('employee')
    # ### end Alembic commands ###
