"""empty message

Revision ID: b37062980417
Revises: 6c2132a57fd8
Create Date: 2026-03-13 12:58:42.536065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b37062980417"
down_revision: Union[str, Sequence[str], None] = "6c2132a57fd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("tax_regime", sa.String(), server_default="MANUAL", nullable=False),
    )
    op.add_column(
        "organization",
        sa.Column(
            "annual_turnover", sa.Numeric(), server_default="0.0", nullable=False
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "fixed_asset_value", sa.Numeric(), server_default="0.0", nullable=False
        ),
    )
    op.add_column(
        "organization", sa.Column("cac_registration_number", sa.String(), nullable=True)
    )
    op.add_column(
        "organization",
        sa.Column(
            "is_vat_registered", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "taxrate",
        sa.Column("tax_type", sa.String(), server_default="VAT", nullable=False),
    )
    op.add_column(
        "taxrate",
        sa.Column(
            "is_recoverable", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "taxrate",
        sa.Column("scope", sa.String(), server_default="BOTH", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("taxrate", "scope")
    op.drop_column("taxrate", "is_recoverable")
    op.drop_column("taxrate", "tax_type")
    op.drop_column("organization", "is_vat_registered")
    op.drop_column("organization", "cac_registration_number")
    op.drop_column("organization", "fixed_asset_value")
    op.drop_column("organization", "annual_turnover")
    op.drop_column("organization", "tax_regime")
    # ### end Alembic commands ###
