"""Add Inventory Item logic

Revision ID: b4f6a30091e6
Revises: 618c37ee0304
Create Date: 2026-03-04 13:58:28.561482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4f6a30091e6'
down_revision: Union[str, Sequence[str], None] = '618c37ee0304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INVENTORY', 'NON_INVENTORY', 'SERVICE', name='itemtype'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('income_account_id', sa.Integer(), nullable=True),
    sa.Column('cogs_account_id', sa.Integer(), nullable=True),
    sa.Column('asset_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['cogs_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['income_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('billlineitem', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billlineitem', 'item', ['item_id'], ['id'])
    op.add_column('invoicelineitem', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoicelineitem', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoicelineitem', type_='foreignkey')
    op.drop_column('invoicelineitem', 'item_id')
    op.drop_constraint(None, 'billlineitem', type_='foreignkey')
    op.drop_column('billlineitem', 'item_id')
    op.drop_table('item')
    # ### end Alembic commands ###
