"""Add bank reconciliation models

Revision ID: b51094de2336
Revises: 87a87c0a0edd
Create Date: 2026-03-03 23:20:12.992374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b51094de2336'
down_revision: Union[str, Sequence[str], None] = '87a87c0a0edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankstatement',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('start_balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('end_balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankstatementline',
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('matched_journal_line_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matched_journal_line_id'], ['ledgerline.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['bankstatement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankstatementline')
    op.drop_table('bankstatement')
    # ### end Alembic commands ###
