"""mfa

Revision ID: dd6d3d8cc27b
Revises: 1c9fe5ac53f4
Create Date: 2026-03-10 23:46:27.548586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dd6d3d8cc27b"
down_revision: Union[str, Sequence[str], None] = "1c9fe5ac53f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "user",
        sa.Column("mfa_secret", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "mfa_secret")
    op.drop_column("user", "mfa_enabled")
    # ### end Alembic commands ###
