"""Add UserRole Enum and role column

Revision ID: f1973aca0afe
Revises: 94026c6e23a6
Create Date: 2026-03-02 19:59:12.475053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f1973aca0afe"
down_revision: Union[str, Sequence[str], None] = "94026c6e23a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use sa.String() instead of Postgres native enums for simpler migrations and lifecycle.
    # We add a server_default='VIEWER' so existing users don't break the NOT NULL constraint.
    op.add_column(
        "user", sa.Column("role", sa.String(), server_default="VIEWER", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
